export CA_CERT_PASSWORD=password
export SERVER_CERT_PASSWORD=password
export SERVER_CERT_CN=localhost
export SERVER_ALT_NAME=localhost
export APPLICATION_NAME=webservice
export KEYSTORE_PASSWORD=password
export TRUSTSTORE_PASSWORD=password